### PR TITLE
Added additional information about bug reports

### LINKED ISSUE #425: No indication of bug reports being exposed publicly
If a user submits a bug report on page `report_bug`, a new issue is created automatically, immediately.
Users are not informed anywhere that these reports are made public as soon as they are created, and might assume that only system administrators will be able to see it and therefore might include personal information. I'm also not sure if organizations using this software have consent from their respective users to publicly disclose the bug with the name of the reporter.

I think this feature should be removed. If a user is capable of submitting a github issue, we could give them a link to this repo. Otherwise, it is much easier to get the report on a more interactive platform (like e-mail), and ask for additional information.

### PR DESCRIPTION
**Pull request by horcsinbalint**
Should fix #425

### CODE REVIEW

File: resources/lang/hu/general.php [hunk 1]
```diff
@@ -34,6 +34,7 @@
     'register_collegist' => 'Jelentkezés collegistának',
     'register_guest' => 'Regisztráció vendégeknek',
     'report_bug' => 'Hiba bejelentése',
+    'report_bug_long_description' => 'Olyan hibákat jelents itt, amelyek az ' . config('app.name') . ' kódját érintik. Amennyiben konfigurációs probléma van vagy személyes adataid hibásak, keresd a rendszergazdákat <a href="mailto:' . config('contacts.mail_sysadmin') . '">e-mail címükön</a>. Az alábbi formon bejelentett hibák a <a href="https://github.com/' . config('github.repo') . '">szoftver publikus github repojában</a> emberi beavatkozás nélkül a bejelentést követően azonnal nyilvánosságra vannak hozva.',
```
Comment (BertalanD) [inline resources/lang/hu/general.php]: Maybe make the wording less intimidating?

```suggestion
    'report_bug_long_description' => 'Olyan hibákat jelents itt, amelyek az ' . config('app.name') . ' kódját érintik. Amennyiben konfigurációs probléma van vagy személyes adataid hibásak, keresd a rendszergazdákat <a href="mailto:' . config('contacts.mail_sysadmin') . '">e-mail címükön</a>. Az alábbi formon bejelentett hibák automatikusan rögzítődnek az ' . config('app.name') . ' <b>nyilvánosan elérhető</b> <a href="https://github.com/' . config('github.repo') . '/issues">fejlesztői hibakövetőjében</a>.',
```

**Review by kdmnk — APPROVED** [review]
