### PR TITLE
Improvements and fixes for the room assignment module

### LINKED ISSUE #70: Pause router pinging on debug mode
We get a lot of unnecessary emails when the routers seem unavailable while the page is in debug mode.

### LINKED ISSUE #123: Add option to select tenants in the room assignment form
If they are still tenants (check the `tenant_until` field)

### PR DESCRIPTION
**Pull request by sszajbely**
- Active tenants are displayed in the selectors
- Room assignment blade uses functions to get users and color of the room
- President can assign tenant role: I added this because I don't want to add externs to the query, but right now they cannot be added to the room assignment. So the new policy should be to add the tenant right to the externs living in the building.
- Made separate page for modifying the room assignment. This should make the loading faster.
- Added email that is sent out to the residents of the room if the router is not available.

### CODE REVIEW

File: app/Http/Controllers/Dormitory/RoomController.php [hunk 1]
```diff
@@ -18,10 +21,26 @@ public function index()
     {
         $this->authorize('viewAny', Room::class);
         $users=User::active()->resident()->get();
-
+        $tenants=User::role(Role::getRole(Role::TENANT), null)->whereHas('personalInformation', function ($q) {
```
Comment (kdmnk) [inline app/Http/Controllers/Dormitory/RoomController.php]: User::role(Role::TENANT)->... is enough

File: app/Http/Controllers/Dormitory/RoomController.php [hunk 2]
```diff
@@ -18,10 +21,26 @@ public function index()
...
+            $q->where('tenant_until', '>', now());
+        })->get();
```
Comment (kdmnk) [inline app/Http/Controllers/Dormitory/RoomController.php]: Add an currentTenants abstract function to the User model

File: app/Models/Room.php [hunk 3]
```diff
@@ -16,10 +16,6 @@ class Room extends Model
 
     protected $fillable = ['name', 'capacity'];
 
-    protected $with = ['users'];
-
-    protected $withCount = ['users'];
-
```
Comment (kdmnk) [inline app/Models/Room.php]: I added these to optimize the queries... Why did you delete it?

File: app/Models/Router.php [hunk 4]
```diff
@@ -53,6 +53,13 @@ public function sendWarning()
             foreach ($internet_admins as $admin) {
                 Mail::to($admin)->queue(new \App\Mail\RouterWarning($admin, $this));
             }
+            $room=Room::firstWhere('name', $this->room);
+            if ($room!=null) {
+                $residents=$room->users()->get();
+                foreach ($residents as $resident) {
```
Comment (kdmnk) [inline app/Models/Router.php]: foreach($room->residents as ...

File: app/Models/Router.php [hunk 5]
```diff
@@ -53,6 +53,13 @@ public function sendWarning()
             foreach ($internet_admins as $admin) {
```
Comment (kdmnk) [inline app/Models/Router.php:53]: Also please do https://github.com/EotvosCollegium/mars/issues/70 also, while you are here

File: app/Policies/UserPolicy.php [hunk 6]
```diff
@@ -137,6 +137,10 @@ public function updateAnyPermission(User $user, User $target, Role $role = null)
             ]);
         }
 
+        if ($role->name == Role::TENANT) {
+            return $user->hasRole([Role::STAFF, Role::STUDENT_COUNCIL => Role::PRESIDENT]);
+        }
```
Comment (kdmnk) [inline app/Policies/UserPolicy.php:142]: Then, you should add the president to the view policy as well (if not there already)

File: resources/views/dormitory/rooms/app.blade.php [hunk 7]
```diff
@@ -124,6 +124,14 @@
                         array_push($colorArray, [ "id" => $room->name, "color" => $color]);
                     }
                     $roomColors=collect($colorArray);
+
+                    function getRoomColor(string|int $roomNumber, $roomColors) {
+                        return $roomColors->where('id',$roomNumber)->pluck('color')->join(',');
+                    }
+
+                    function getRoomResidents(string|int $roomNumber, \Illuminate\Database\Eloquent\Collection $rooms){
+                        return $rooms->firstWhere('name', $roomNumber)->users()->get()->pluck('name')->join(';');
```
Comment (kdmnk) [inline resources/views/dormitory/rooms/app.blade.php]: Do not add functions to blade files, please :D

**Review by kdmnk — CHANGES_REQUESTED** [review]

File: app/Models/Room.php (hunk 3 above)
Comment (sszajbely) [reply app/Models/Room.php]: It doesn't work. If I type $room->users it returns the first user, not all of them. Just $room->users()->get() works for some reason

File: resources/views/dormitory/rooms/app.blade.php (hunk 7 above)
Comment (sszajbely) [reply resources/views/dormitory/rooms/app.blade.php]: And where should they be then? Like this it does not look like shit :D

File: app/Models/Room.php (hunk 3 above)
Comment (kdmnk) [reply app/Models/Room.php]: - still, you've multiplied tenfold the number of queries :P
- I checked, the relation was bad from those rooms' side. Please modify it as `return $this->hasMany(User::class, 'room', 'name');`

**Comment by kdmnk** [comment]
I also noticed some other things:
- RoomController - updateResidents:
instead of:
```
        foreach ($users as $user) {
            $user->update(['room' => null]);
        }
```
`$users->update(['room' => null]);` is enough

- Currently, when a user has been selected for two different users, the system will only store it for the latter room without any warnings.
- Actually, I would prefer to have this as a livewire page, this way we can also display only the users without any room for selection. Do you want to do that?

File: resources/views/dormitory/rooms/app.blade.php (hunk 7 above)
Comment (kdmnk) [reply resources/views/dormitory/rooms/app.blade.php]: I'd make an attribute getter for the room model that returns the colour accordingly and the names as a string. Then,  you can make one big array with different attributes in the controller and pass it to the view. I want to avoid using PHP in blades as much as possible

File: resources/views/dormitory/rooms/app.blade.php [hunk 8]
```diff
@@ -145,46 +153,46 @@
...
+                        <path id="room224" style="fill: {{getRoomColor(224, $roomColors)}}" data-info="{{ getRoomResidents(224, $rooms) }}" class="st1" d="M174.9,525.5h51.4l-0.2,92l-51.4,0.4L174.9,525.5z"/>
+                        <path id="room223" style="fill: {{getRoomColor(223, $roomColors)}}" data-info="{{ getRoomResidents(223, $rooms) }}" class="st1" d="M228.6,525.5l43.4,0.4l0.2,91.9h-44.2v-92.2H228.6z"/>
+                        <path id="room222" style="fill: {{getRoomColor(222, $roomColors)}}" data-info="{{ getRoomResidents(222, $rooms) }}" class="st1" d="M274.5,525.5l47.9,0.2l0.6,91.9l-48.5,0.2L274.5,525.5z"/>
+                        <path id="room221" style="fill: {{getRoomColor(221, $roomColors)}}" data-info="{{ getRoomResidents(221, $rooms) }}" class="st1" d="M324.4,525.5h46.4v92l-46.4,0.2V525.5z"/>
+                        <path id="room220" style="fill: {{getRoomColor(220, $roomColors)}}" data-info="{{ getRoomResidents(220, $rooms) }}" class="st1" d="M372.5,525.5l51.1,0.2l-0.4,92h-50.5L372.5,525.5z"/>
```
Comment (kdmnk) [inline resources/views/dormitory/rooms/app.blade.php]: Instead of the style, use the materialize colour classes (https://materializecss.github.io/materialize/color.html), also you can get it from the model.
For the coordinates (and every other variable attribute), paste them into a new file (like we did with the countries), and you can also load them in the controller.
This way, you can make this in a foreach.

**Comment by sszajbely** [comment]
> I also noticed some other things:
> 
> * RoomController - updateResidents:
>   instead of:
> 
> ```
>         foreach ($users as $user) {
>             $user->update(['room' => null]);
>         }
> ```
> 
> `$users->update(['room' => null]);` is enough

It doesn't seem to work for me. I get an error: `Method Illuminate\Database\Eloquent\Collection::update does not exist.`
@kdmnk

File: resources/views/dormitory/rooms/app.blade.php (hunk 8 above)
Comment (sszajbely) [reply resources/views/dormitory/rooms/app.blade.php]: Sadly I need the `fill ` CSS property to change not the `background-color`, so I couldn't use the materialize classes. But I tried my best to make the code readable in this regard.

**Comment by kdmnk** [comment]
> > I also noticed some other things:
> > 
> > * RoomController - updateResidents:
> >   instead of:
> > 
> > ```
> >         foreach ($users as $user) {
> >             $user->update(['room' => null]);
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `$users->update(['room' => null]);` is enough
> 
> It doesn't seem to work for me. I get an error: `Method Illuminate\Database\Eloquent\Collection::update does not exist.` @kdmnk

Oh, yeah, you need this before get the users from db. So User::update(['room' => null]), and you do not even need the $users var.

File: app/Models/Room.php [hunk 9]
```diff
@@ -20,12 +20,19 @@ class Room extends Model
 
     protected $withCount = ['users'];
 
+    public static $roomColors = [
+        3 => '#76ff03', //light-green accent-3
+        2 => '#ffee58', //yellow lighten-2
+        1 => '#ff9100', //orange accent-2
+        0 => '#e0e0e0', //grey lighten-2
```
Comment (kdmnk) [inline app/Models/Room.php:27]: I meant you do not need to use the # values. Pass 'light-green accent-3' as a css class.

Comment (kdmnk) [reply app/Models/Room.php:27]: And you do not need this attribute. Just return them in the color() function. Or do you use this elsewhere?

File: app/Models/Router.php [hunk 10]
```diff
@@ -48,11 +48,17 @@ public function getFailStartDate()
 
     public function sendWarning()
     {
-        if ($this->failed_for == self::WARNING_THRESHOLD) {
+        if ($this->failed_for == self::WARNING_THRESHOLD && env('APP_DEBUG') == false) {
```
Comment (kdmnk) [inline app/Models/Router.php]: I meant do not increment the failed_for attribute if the app is in debug mode. I'm afraid  this way we still get emails after changing back to prod.

**Review by kdmnk — CHANGES_REQUESTED** [review]
Okay, nice. Left some comments, otherwise, after that  can merge this. I'll do the livewire thing sometime.

File: app/Models/Room.php (hunk 9 above)
Comment (sszajbely) [reply app/Models/Room.php:27]: I generate the legend using the attribute. And as I wrote, the color classes set the `background-color` style property and in svg I need to change the `fill `property.

**Comment by sszajbely** [comment]
> > > I also noticed some other things:
> > > 
> > > * RoomController - updateResidents:
> > >   instead of:
> > > 
> > > ```
> > >         foreach ($users as $user) {
> > >             $user->update(['room' => null]);
> > >         }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `$users->update(['room' => null]);` is enough
> > 
> > 
> > It doesn't seem to work for me. I get an error: `Method Illuminate\Database\Eloquent\Collection::update does not exist.` @kdmnk
> 
> Oh, yeah, you need this before get the users from db. So User::update(['room' => null]), and you do not even need the $users var.

`Non-static method Illuminate\Database\Eloquent\Model::update() cannot be called statically` I think I'll stay with the one that works :D

**Review by kdmnk — APPROVED** [review]
